### ISSUE TITLE
Developing with ArcGIS Open Data

### ISSUE THREAD

**Issue by mjuniper** [mjuniper/presentations#1]
03/12, 5:30 - 6:30, Mesquite GH

http://webapps-cdn.esri.com/Apps/EventsAppCordova/www/index.html#@view=eventSessions@con=90@mode=list@dataset=sessions@feature=19023

>Get a firsthand look at working with the ArcGIS Open Data API’s, to build your own open data site or next popular dashboard application that propel transparency to the next level. You will also see how to expose your open data catalog as DCAT to promote interoperability with other open platforms, and melt your mind with space cats.

1. Intro - 5 mins
  1. What is ArcGIS Open Data?
    1. Our basic customization story.
    1. But if that's not enough....
  1. What are we going to talk about?
1. koop - bring data exposed by other APIs into open data - 5 mins
1. dcat, opensearch - make your open data available in other systems - no developer necessary - 5 - 10 mins (daniel)
1. REST API - 15 - 20 mins (brooks, alex?)
1. Building something agains the API - Opendata sample - 15 - 20 mins
  1. Demo
  1. How i built it
    1. `/datasets.json`, `/datasets/<id>.json` (and a little `/autocomplete?query=`)
    1. In Backbone that just means giving your model/collection a `url` property or method.
  1. You could build one from scratch in the same way
  1. Or you could fork it
  1. More coming? (ember, angular, ampersand)
1. Questions - 5 - 10 mins

**Comment by ajturner** [comment]
@mjuniper I suggest keeping it simple to start then getting more complex - Intro, then DCAT + OpenSearch, REST API, Open Data Starter, finally koop.
